# Generated by Django 5.1.6 on 2025-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('crm', models.CharField(max_length=11, unique=True)),
                ('senha', models.CharField(max_length=128, null=True)),
                ('especialidade', models.CharField(max_length=255)),
            ],
        ),
    ]
