# Generated by Django 5.1.6 on 2025-03-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='consutório',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.medico'),
        ),
    ]
