# Generated by Django 5.1.6 on 2025-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medico_consutório_alter_consulta_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='consutório',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.CharField(max_length=255),
        ),
    ]
