# Generated by Django 5.1.6 on 2025-03-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_medico_consutório_alter_consulta_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='consultório',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.medico'),
        ),
    ]
