# Generated by Django 5.1.6 on 2025-03-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_medico_consultório_alter_consulta_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='consultório',
            new_name='consultorio',
        ),
    ]
