# Generated by Django 5.1.6 on 2025-03-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_consultório_medico_consultorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
    ]
