# Generated by Django 5.1.6 on 2025-03-13 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_consulta_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.medico'),
        ),
    ]
