# Generated by Django 5.1.6 on 2025-03-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_consulta_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(max_length=128),
        ),
    ]
