# Generated by Django 5.1.6 on 2025-03-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paciente_sintomas_alter_medico_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando confirmação'), ('confirmada', 'Confirmada')], default='aguardando', max_length=20),
        ),
    ]
