# Generated by Django 5.1.6 on 2025-03-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_consulta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sintomas',
        ),
    ]
