# Generated by Django 5.1.6 on 2025-03-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_paciente_sintomas'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='sintomas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
