# Generated by Django 5.1.6 on 2025-03-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_consulta_sintomas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='consulta',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='agendada', max_length=20),
        ),
    ]
