# Generated by Django 5.1.6 on 2025-03-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_consulta_sintomas_consulta_data_cancelamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='aguardando', max_length=20),
        ),
    ]
