# Generated by Django 5.1.6 on 2025-04-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_consulta_options_consulta_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
