# Generated by Django 5.1.6 on 2025-04-01 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_consulta_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_cancelamento',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='aguardando', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsultaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta_original_id', models.IntegerField(null=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
            ],
        ),
    ]
