# Generated by Django 5.1.6 on 2025-04-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_estatisticas_consulta_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='agendada', max_length=20),
        ),
    ]
