# Generated by Django 5.1.6 on 2025-04-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_consulta_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='retorno_ou_primeira_consulta',
            field=models.CharField(choices=[('retorno', 'Paciente retornando'), ('primeira_consulta', 'Primeira consulta do paciente')], default='primeira_consulta', max_length=20),
        ),
    ]
