# Generated by Django 5.1.6 on 2025-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.TextField(max_length=128)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
    ]
