# Generated by Django 5.1.6 on 2025-03-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0002_remove_paciente_senha_paciente_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='password',
        ),
        migrations.AddField(
            model_name='paciente',
            name='senha',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
