# Generated by Django 5.1.6 on 2025-03-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0004_alter_paciente_cpf_alter_paciente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='sus.paciente'),
        ),
    ]
