# Generated by Django 5.1.6 on 2025-03-09 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0005_alter_consulta_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='senha',
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
