# Generated by Django 5.1.6 on 2025-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0006_remove_paciente_nome_remove_paciente_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
