# Generated by Django 5.1.6 on 2025-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0007_remove_paciente_user_paciente_nome_paciente_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='senha',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
