# Generated by Django 5.1.6 on 2025-03-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0008_alter_paciente_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
